### ISSUE TITLE
Feature request: use socketcan

### ISSUE THREAD

**Issue by slundell** [SmartBoatInnovations/ha-smart2000usb#1]
Hi!

I have a waveshare baseboard for compute module 4. It has, as man pi hats have, an mpc2515 can module connected via spi on a gpio. It shows up as a network device in raspberry os as /dev/can0. Opening that with candump gives a stream of nmea messages. I ordered a usb can stick just for this integration, but it would have been nice to use the built in.

Would it be possible for this integration to use socketcan as well?

**Comment by SmartBoatInnovations** [comment]
Unfortunately, with Home Assistant OS (HAOS), it is not possible to directly access GPIO pins, which includes the SPI interface required for the MCP2515 CAN module. This is due to the managed environment of HAOS, which abstracts hardware access to maintain a secure and stable system. As a result, integrating SocketCAN directly within HAOS is also not feasible.The aim of my integrations is to support installations of Home Assistant OS where the environment is tightly managed by Home Assistant. This ensures ease of use and reliability but does come with some hardware access limitations.

**Comment by slundell** [comment]
I understand, but once you have provisioned the pi you do not need to do anything low level. You can just access /dev/can0 which I guess should be able to access even in HAOS. I do not know much about the haos container isolation though

**Comment by SmartBoatInnovations** [comment]
HAOS is very restricted. System calls are resticted. I have tried with other adapters and it would not work. HAOS does not support the socket CAN driver.

**Comment by SmartBoatInnovations** [comment]
Closed
